// <auto-generated/>
#nullable enable

namespace ForceSourceGenCodeOutput
{
    internal partial class SimplePocoForSerialisationContext
    {
        
        private static readonly global::System.Text.Json.JsonEncodedText PropName_firstName = global::System.Text.Json.JsonEncodedText.Encode("firstName");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_lastName = global::System.Text.Json.JsonEncodedText.Encode("lastName");
    }
}
