// <auto-generated/>
#nullable enable

namespace ForceSourceGenCodeOutput
{
    internal partial class SimplePocoForSerialisationContext
    {
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo GetTypeInfo(global::System.Type type)
        {
            if (type == typeof(global::ForceSourceGenCodeOutput.SimplePocoForSerialisation))
            {
                return this.SimplePocoForSerialisation;
            }
        
            return null!;
        }
    }
}
